# **Meeple Analytics**

**1. Objetivo del proyecto**

**Cliente**

Editorial internacional de juegos de mesa.

**Problema**

La empresa quiere entender qué factores influyen en el éxito de un juego para orientar futuras inversiones y lanzamientos.

**1- Revisar nulos:**

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# Cargar dataset
df = pd.read_csv("games.csv")

# Información general
print(df.shape)

(21925, 48)

In [4]:
df.head()

,BGGId,Name,Description,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
0,1,Die Macher,die macher game seven sequential political rac...,1986,4.3206,7.61428,7.10363,1.57979,3,5,...,21926,21926,0,1,0,0,0,0,0,0
1,2,Dragonmaster,dragonmaster tricktaking card game base old ga...,1981,1.9630,6.64537,5.78447,1.45440,3,4,...,21926,21926,0,1,0,0,0,0,0,0
2,3,Samurai,samurai set medieval japan player compete gain...,1998,2.4859,7.45601,7.23994,1.18227,2,4,...,21926,21926,0,1,0,0,0,0,0,0
3,4,Tal der Könige,triangular box luxurious large block tal der k...,1992,2.6667,6.60006,5.67954,1.23129,2,4,...,21926,21926,0,0,0,0,0,0,0,0
4,5,Acquire,acquire player strategically invest business t...,1964,2.5031,7.33861,7.14189,1.33583,2,6,...,21926,21926,0,1,0,0,0,0,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21925 entries, 0 to 21924
Data columns (total 48 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BGGId                21925 non-null  int64
 1   Name                 21925 non-null  object
 2   Description          21924 non-null  object
 3   YearPublished        21925 non-null  int64
 4   GameWeight           21925 non-null  float64
 5   AvgRating            21925 non-null  float64
 6   BayesAvgRating       21925 non-null  float64
 7   StdDev               21925 non-null  float64
 8   MinPlayers           21925 non-null  int64
 9   MaxPlayers           21925 non-null  int64
 10  ComAgeRec            16395 non-null  float64
 11  LanguageEase         16034 non-null  float64
 12  BestPlayers          21925 non-null  int64
 13  GoodPlayers          21925 non-null  object
 14  NumOwned             21925 non-null  int64
 15  NumWant              21925 non-null  int64
 16  NumWish              21925 non-null  int64
 17  NumWeightVotes       21925 non-null  int64
 18  MfgPlaytime          21925 non-null  int64
 19  ComMinPlaytime       21925 non-null  int64
 20  ComMaxPlaytime       21925 non-null  int64
 21  MfgAgeRec            21925 non-null  int64
 22  NumUserRatings       21925 non-null  int64
 23  NumComments          21925 non-null  int64
 24  NumAlternates        21925 non-null  int64
 25  NumExpansions        21925 non-null  int64
 26  NumImplementations   21925 non-null  int64
 27  IsReimplementation   21925 non-null  int64
 28  Family               6663 non-null   object
 29  Kickstarted          21925 non-null  int64
 30  ImagePath            21908 non-null  object
 31  Rank:boardgame       21925 non-null  int64
 32  Rank:strategygames   21925 non-null  int64
 33  Rank:abstracts       21925 non-null  int64
 34  Rank:familygames     21925 non-null  int64
 35  Rank:thematic        21925 non-null  int64
 36  Rank:cgs             21925 non-null  int64
 37  Rank:wargames        21925 non-null  int64
 38  Rank:partygames      21925 non-null  int64
 39  Rank:childrensgames  21925 non-null  int64
 40  Cat:Thematic         21925 non-null  int64
 41  Cat:Strategy         21925 non-null  int64
 42  Cat:War              21925 non-null  int64
 43  Cat:Family           21925 non-null  int64
 44  Cat:CGS              21925 non-null  int64
 45  Cat:Abstract         21925 non-null  int64
 46  Cat:Party            21925 non-null  int64
 47  Cat:Childrens        21925 non-null  int64
dtypes: float64(6), int64(37), object(5)
memory usage: 8.0+ MB

In [6]:
df.isnull().sum().sort_values(ascending=False)

Family                 15262
LanguageEase            5891
ComAgeRec               5530
ImagePath                 17
Description                1
AvgRating                  0
GameWeight                 0
BGGId                      0
StdDev                     0
BayesAvgRating             0
MaxPlayers                 0
MinPlayers                 0
BestPlayers                0
GoodPlayers                0
Name                       0
YearPublished              0
NumWant                    0
NumOwned                   0
NumWish                    0
NumWeightVotes             0
ComMaxPlaytime             0
MfgAgeRec                  0
MfgPlaytime                0
ComMinPlaytime             0
NumComments                0
NumUserRatings             0
NumAlternates              0
NumExpansions              0
IsReimplementation         0
NumImplementations         0
Kickstarted                0
Rank:boardgame             0
Rank:strategygames         0
Rank:abstracts             0
Rank:familygames           0
Rank:thematic              0
Rank:cgs                   0
Rank:wargames              0
Rank:partygames            0
Rank:childrensgames        0
Cat:Thematic               0
Cat:Strategy               0
Cat:War                    0
Cat:Family                 0
Cat:CGS                    0
Cat:Abstract               0
Cat:Party                  0
Cat:Childrens              0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

Tras ver los nulos y duplicados y el aporte que esas columnas hacen al analisis, se decide eliminar:

**Description:** por ser una descripcion de texto libre de los juegos
**Imagepath:** por tratarse solo de la ruta de la imagen del juego que no aporta análisis estadístico ni visualizaciones de negocio.

en cambio, a pesar de su cantidad de nulos no eliminamos las siguientes:

**Family:** Tiene muchos nulos porque muchos juegos no pertenecen a una franquicia. Pero podría permitir preguntas como:

*¿Las franquicias venden mejor que los juegos independientes?*

**LanguageEase:** Esta variable es bastante rara y muy interesante.

Mide el nivel de dependencia del idioma de un juego, lo necesario que es para jugarlo.

Ejemplo:

Ajedrez → muy fácil lingüísticamente
Sherlock Holmes Consulting Detective → muy dependiente del idioma

Pregunta de negocio:

*¿Los juegos más accesibles internacionalmente reciben mejores valoraciones?*

Eso podría dar una conclusión muy potente para una editorial.

**ComAgeRec vs MfgAgeRec**

Tiene dos variables:

*ComAgeRec*

Edad recomendada por la comunidad.

*MfgAgeRec*

Edad recomendada por el fabricante.

Esto permite responder una pregunta muy interesante:

¿Los jugadores consideran que los juegos son adecuados para edades diferentes a las recomendadas por la empresa?
*texto en cursiva*
Quiza necesitemos responder a estas preguntas más adelante.

In [8]:
df = df.drop(
    columns=["Description", "ImagePath"],
    errors="ignore"
)

df.columns.tolist()

['BGGId',
 'Name',
 'YearPublished',
 'GameWeight',
 'AvgRating',
 'BayesAvgRating',
 'StdDev',
 'MinPlayers',
 'MaxPlayers',
 'ComAgeRec',
 'LanguageEase',
 'BestPlayers',
 'GoodPlayers',
 'NumOwned',
 'NumWant',
 'NumWish',
 'NumWeightVotes',
 'MfgPlaytime',
 'ComMinPlaytime',
 'ComMaxPlaytime',
 'MfgAgeRec',
 'NumUserRatings',
 'NumComments',
 'NumAlternates',
 'NumExpansions',
 'NumImplementations',
 'IsReimplementation',
 'Family',
 'Kickstarted',
 'Rank:boardgame',
 'Rank:strategygames',
 'Rank:abstracts',
 'Rank:familygames',
 'Rank:thematic',
 'Rank:cgs',
 'Rank:wargames',
 'Rank:partygames',
 'Rank:childrensgames',
 'Cat:Thematic',
 'Cat:Strategy',
 'Cat:War',
 'Cat:Family',
 'Cat:CGS',
 'Cat:Abstract',
 'Cat:Party',
 'Cat:Childrens']

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
BGGId,21925.0,117652.663216,104628.721777,1.000000,12346.000000,105305.00000,206169.00000,349161.00000
YearPublished,21925.0,1985.494914,212.486214,-3500.000000,2001.000000,2011.00000,2017.00000,2021.00000
GameWeight,21925.0,1.982131,0.848983,0.000000,1.333300,1.96880,2.52520,5.00000
AvgRating,21925.0,6.424922,0.932477,1.041330,5.836960,6.45395,7.05245,9.91429
BayesAvgRating,21925.0,5.685673,0.365311,3.574810,5.510300,5.54654,5.67989,8.51488
StdDev,21925.0,1.516374,0.285578,0.196023,1.320720,1.47688,1.66547,4.27728
MinPlayers,21925.0,2.007343,0.693093,0.000000,2.000000,2.00000,2.00000,10.00000
MaxPlayers,21925.0,5.707868,15.014643,0.000000,4.000000,4.00000,6.00000,999.00000
ComAgeRec,16395.0,10.004391,3.269157,2.000000,8.000000,10.00000,12.00000,21.00000
LanguageEase,16034.0,216.461819,236.595136,1.000000,24.027778,138.00000,351.00000,1757.00000
BestPlayers,21925.0,0.311517,1.067002,0.000000,0.000000,0.00000,0.00000,15.00000
NumOwned,21925.0,1467.848164,5294.120574,0.000000,150.000000,320.00000,899.00000,166497.00000
NumWant,21925.0,41.690946,117.255229,0.000000,3.000000,9.00000,28.00000,2031.00000
NumWish,21925.0,228.457013,788.477151,0.000000,14.000000,39.00000,127.00000,19182.00000
NumWeightVotes,21925.0,49.480137,205.762375,0.000000,4.000000,9.00000,26.00000,7673.00000
MfgPlaytime,21925.0,90.513523,529.657389,0.000000,25.000000,45.00000,90.00000,60000.00000
ComMinPlaytime,21925.0,63.678586,443.916212,0.000000,20.000000,30.00000,60.00000,60000.00000
ComMaxPlaytime,21925.0,90.513523,529.657389,0.000000,25.000000,45.00000,90.00000,60000.00000
MfgAgeRec,21925.0,9.613409,3.641560,0.000000,8.000000,10.00000,12.00000,25.00000
NumUserRatings,21925.0,861.668324,3638.680857,30.000000,56.000000,123.00000,395.00000,108101.00000
NumComments,21925.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000
NumAlternates,21925.0,1.603786,9.619364,0.000000,0.000000,0.00000,1.00000,850.00000
NumExpansions,21925.0,1.380068,7.701036,0.000000,0.000000,0.00000,1.00000,525.00000
NumImplementations,21925.0,0.308734,0.848095,0.000000,0.000000,0.00000,0.00000,38.00000
IsReimplementation,21925.0,0.116762,0.321143,0.000000,0.000000,0.00000,0.00000,1.00000
Kickstarted,21925.0,0.153341,0.360324,0.000000,0.000000,0.00000,0.00000,1.00000
Rank:boardgame,21925.0,11019.514071,6372.926817,1.000000,5488.000000,11022.00000,16544.00000,21926.00000
Rank:strategygames,21925.0,19729.826956,6389.614077,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:abstracts,21925.0,20839.347184,4695.170448,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:familygames,21925.0,19732.270011,6387.089598,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:thematic,21925.0,20736.185815,4893.928466,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:cgs,21925.0,21625.086796,2542.033794,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:wargames,21925.0,18680.185678,7420.906104,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:partygames,21925.0,21295.352201,3637.139987,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Rank:childrensgames,21925.0,21062.680274,4219.776597,1.000000,21926.000000,21926.00000,21926.00000,21926.00000
Cat:Thematic,21925.0,0.055827,0.229592,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:Strategy,21925.0,0.105770,0.307550,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:War,21925.0,0.161003,0.367542,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:Family,21925.0,0.105633,0.307374,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:CGS,21925.0,0.013820,0.116745,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:Abstract,21925.0,0.050855,0.219707,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:Party,21925.0,0.029190,0.168344,0.000000,0.000000,0.00000,0.00000,1.00000
Cat:Childrens,21925.0,0.040182,0.196391,0.000000,0.000000,0.00000,0.00000,1.00000

Hay juegos tradicionales y clásicos como ajedrez o mancala, queremos saber en qué juegos de nueva creacion invertir basándonos en el auge actual de los juegos modernos, asi que se vana a eliminar todos los juegos anteriores a 1950

In [10]:
df_clean = df[df["YearPublished"] >= 1950].copy()

In [11]:
df.nlargest(10, "MaxPlayers")[["Name", "MaxPlayers"]]

                                                  Name  MaxPlayers
7327       Start Player: A Kinda Collectible Card Game         999
7743           I Don't Know, What Do You Want to Play?         999
15467                               Scrimish Card Game         999
2568   The Hammer of Thor: The Game of Norse Mythology         362
12771                                          Linkee!         200
7322                        Pit Fighter: Fantasy Arena         163
15221                                       Alchemidus         127
9552                      Black Powder: Second Edition         120
544                                         Fairy Meat         100
1977                                      Rapid Recall         100

En un principio puede parecer que hay errores en el numero total de jugadores, pero algunos juegos pueden admitir grupos muy grandes y el 999 muchas veces significa:

"Prácticamente sin límite de jugadores"

No es un error de captura, sino una forma de codificar una característica especial del juego.

Por ello no vamos a eliminar nada, pero si vamos a añadir una nueva variable para ordenarlos.

In [14]:
def classify_players(x):
    if x <= 2:
        return "2 Players"
    elif x <= 5:
        return "3-5 Players"
    elif x <= 10:
        return "6-10 Players"
    else:
        return "Large Groups"

df_clean["PlayerSegment"] = (
    df_clean["MaxPlayers"]
      .apply(classify_players)
)

In [13]:
df[df["MfgPlaytime"] > 1000][
    ["Name", "MfgPlaytime"]
]

                                                    Name  MfgPlaytime
217                                      Empires in Arms        12000
243                                 Advanced Third Reich         2480
285                                        Russian Front         1200
622                            Turning Point: Stalingrad         1800
1117                                     World in Flames         6000
...                                                  ...          ...
20618  The Jaws of Victory: Battle of Korsun-Cherkass...         3000
20789                       1985: Deadly Northern Lights         5000
21597  Don't Get Got!: Shut Up & Sit Down Special Edi...         1440
21614     Panzers Last Stand: Battles for Budapest, 1945         1560
21759                 Sleeping Gods: Kickstarter Edition         1200

[122 rows x 2 columns]

Como pasa en el caso anterior, debido a que hay juegos de duraciones indefinidas, como juegos de campaña que dependen de decisiones de los jugadores, tampoco podemos contar como outliers los que marcan una cantidad de horas que se sale de lo comun.
Pot tanto, se concluye que estos valores no son errores de captura sino características inherentes a determinados tipos de juegos (juegos de rol, campañas narrativas o juegos para grupos numerosos). Por ello se decide mantener dichos registros y documentar su impacto potencial en las visualizaciones.

In [15]:
df.to_csv(
    "games_clean.csv",
    index=False
)

In [17]:
from google.colab import files

files.download("games_clean.csv")